name: MovieCatalog

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore MoviesExam.sln

    - name: Build
      run: dotnet build MoviesExam.sln --configuration ${{ matrix.configuration }}

    - name: Test
      run: dotnet test MoviesExam.sln --configuration ${{ matrix.configuration }}
